version: '3.8'
services:
  web:
    build:
      context: .
      args:
        - MONGO_URI=${MONGO_URI}
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_APP_CLIENT_ID=${GOOGLE_APP_CLIENT_ID}
      - GOOGLE_APP_CLIENT_SECRET=${GOOGLE_APP_CLIENT_SECRET}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 