name: Deploy to Aliyun

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required secrets
        run: |
          [[ -z "${{ secrets.MONGO_URI }}" ]] && echo "Missing MONGO_URI" && exit 1
          [[ -z "${{ secrets.NEXTAUTH_SECRET }}" ]] && echo "Missing NEXTAUTH_SECRET" && exit 1
          [[ -z "${{ secrets.NEXTAUTH_URL }}" ]] && echo "Missing NEXTAUTH_URL" && exit 1
          [[ -z "${{ secrets.GOOGLE_APP_CLIENT_ID }}" ]] && echo "Missing GOOGLE_APP_CLIENT_ID" && exit 1
          [[ -z "${{ secrets.GOOGLE_APP_CLIENT_SECRET }}" ]] && echo "Missing GOOGLE_APP_CLIENT_SECRET" && exit 1
          [[ -z "${{ secrets.ALIYUN_USERNAME }}" ]] && echo "Missing ALIYUN_USERNAME" && exit 1
          [[ -z "${{ secrets.ALIYUN_PASSWORD }}" ]] && echo "Missing ALIYUN_PASSWORD" && exit 1
          [[ -z "${{ secrets.ECS_HOST }}" ]] && echo "Missing ECS_HOST" && exit 1
          [[ -z "${{ secrets.ECS_USERNAME }}" ]] && echo "Missing ECS_USERNAME" && exit 1
          [[ -z "${{ secrets.ECS_SSH_KEY }}" ]] && echo "Missing ECS_SSH_KEY" && exit 1
          echo "All required secrets are set"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Aliyun Container Registry
        uses: aliyun/acr-login@v1
        with:
          login-server: crpi-ne97tccqwbmfjjvf.cn-shanghai.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 显示系统信息
          df -h
          docker info
          # 使用 buildx 构建
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --platform linux/amd64 \
            --progress=plain \
            --push \
            -t crpi-ne97tccqwbmfjjvf.cn-shanghai.personal.cr.aliyuncs.com/temple_22/temple-h5-editor:$IMAGE_TAG \
            --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
            .

      - name: Deploy to ECS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_SSH_KEY }}
          script: |
            cd /app/temple-h5-editor
            
            cat > docker-compose.yml << 'EOL'
            version: '3.8'
            services:
              web:
                image: crpi-ne97tccqwbmfjjvf.cn-shanghai.personal.cr.aliyuncs.com/temple_22/temple-h5-editor:${IMAGE_TAG}
                ports:
                  - "3000:3000"
                environment:
                  - MONGO_URI=${{ secrets.MONGO_URI }}
                  - NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
                  - NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
                  - GOOGLE_APP_CLIENT_ID=${{ secrets.GOOGLE_APP_CLIENT_ID }}
                  - GOOGLE_APP_CLIENT_SECRET=${{ secrets.GOOGLE_APP_CLIENT_SECRET }}
                restart: always
            EOL
            
            echo "IMAGE_TAG=${{ github.sha }}" > .env
            docker-compose pull
            docker-compose up -d
