name: Deploy to Aliyun

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Aliyun Container Registry
        uses: aliyun/acr-login@v1
        with:
          login-server: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t crpi-ne97tccqwbmfjjvf.cn-shanghai.personal.cr.aliyuncs.com/temple_22/temple-h5-editor:$IMAGE_TAG . --build-arg MONGO_URI=${{ secrets.MONGO_URI }}
          docker push crpi-ne97tccqwbmfjjvf.cn-shanghai.personal.cr.aliyuncs.com/temple_22/temple-h5-editor:$IMAGE_TAG

      - name: Deploy to ECS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_SSH_KEY }}
          script: |
            cd /app/temple-h5-editor
            
            cat > docker-compose.yml << 'EOL'
            version: '3.8'
            services:
              web:
                image: crpi-ne97tccqwbmfjjvf.cn-shanghai.personal.cr.aliyuncs.com/temple_22/temple-h5-editor:${IMAGE_TAG}
                ports:
                  - "3000:3000"
                environment:
                  - MONGO_URI=${{ secrets.MONGO_URI }}
                  - NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
                  - NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
                  - GOOGLE_APP_CLIENT_ID=${{ secrets.GOOGLE_APP_CLIENT_ID }}
                  - GOOGLE_APP_CLIENT_SECRET=${{ secrets.GOOGLE_APP_CLIENT_SECRET }}
                restart: always
            EOL
            
            echo "IMAGE_TAG=${{ github.sha }}" > .env
            docker-compose pull
            docker-compose up -d